### ISSUE TITLE
Thoughts on typed data?

### ISSUE THREAD

**Issue by bbarr** [denyncrawford/dndb#10]
I love the memory-efficient reads/writes of dndb but also love the "typescript by default" nature of Deno. Would you be interested in some help implementing something that looks like:

```typescript
const db = new Datastore<{ name: string, age: number }>({ filename:"./database.db", autoload: true })
```

**Comment by denyncrawford** [comment]
I'm definitely interested, I'm in my way to understand Typescript enough to stop putting anys everywhere haha. I am currently working with a friend on improving storage performance and maybe I've been letting this things out the table, but a help never hurts, thanks dude! Excuse my english by the way!

**Comment by bbarr** [comment]
Ok! I have a fork and will start poking around at it this week. Closing this for now.
