### ISSUE TITLE
type errors with any's

### ISSUE THREAD

**Issue by twilson63** [denyncrawford/dndb#11]
Hello 👋 

Neat Project! I am looking for something of a lite nosql db for small docs and found this project.

When I went to work with it using typescript, I ran into a few type warnings with the any type.

So I added some types to the src/mod.ts file, would you be interested in reviewing and see it this is worthy of a PR?

If you get a chance check it out. - https://github.com/hyper63/dndb/blob/main/src/mod.ts

It did make my type errors go away, but I had to use ts-ignore, which I know is not great, I will have to look into better solutions to add types to the executor add function, since it may return different results based on the initial argument.

Thanks again for the project, if this change is in the direction you are looking for, let me know and I will submit a PR.

Cheers!

**Comment by denyncrawford** [comment]
Hi dude 👋  , I was checking and I see you got rid of the ts-ignore, amazing! So when you have all the changes ready, list them in the PR to review and merge them. Thanks for getting involved with DnDB, big changes are coming.

**Comment by denyncrawford** [comment]
Done, this will be available at 0.3.3 this Monday, thank you mate!
