### ISSUE TITLE
any plans for aggregation?

### ISSUE THREAD

**Issue by ralyodio** [denyncrawford/dndb#7]

**Comment by denyncrawford** [comment]
Yes: I am currently working on some functions and fixing some things for a major version and I am trying to get DnDB to have a more advanced method for computing results, but for now the plans are delayed for time reasons and there are more important things that need to be fixed first :/ , but we currently support these query operators https://github.com/denyncrawford/safe-filter/

If you want to help me improve this module, I am always looking for maintainers! also hope another version can be released soon, but for now I'm more stuck with efficiency issues and solving some edge cases than adding features.

I'll leave the issue open for a while, regards.
