### ISSUE TITLE
Forced to add callback

### ISSUE THREAD

**Issue by fangmarks** [denyncrawford/dndb#8]
In your README for dndb you say that a callback for insert is optional, but when i use it, Type yells at me and tells me that I have to add a callback

![image](https://user-images.githubusercontent.com/20520193/111885932-f0b93200-89ca-11eb-9424-8e981403aba3.png)

I think you only need to add a ? after `cb`

**Comment by fangmarks** [comment]
I'll put in a PR later to fix it

**Comment by denyncrawford** [comment]
Yes buddy, it's a silly mistake, sorry. If you want to fix it, go ahead, it's great for me that there are people interested in improving DnDB, thanks.
